// SIGNUP
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// FLASH
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
